title: Strata by HTML5 UP
description: >
  **I am Kyle**, a student studying Software Engineering.
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://kyle.im
disqus_shortname: 
facebook_username:
twitter_username: ""
linkedin_username: "kylejmccann"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "kylemccann"
feed_icon: rss
email: "hello@kyle.im"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
